Make efaLiveSetup start script call proper Python module

diff --git a/python/efaLiveSetup/efalive-setup b/python/efaLiveSetup/efalive-setup
--- a/python/efaLiveSetup/efalive-setup
+++ b/python/efaLiveSetup/efalive-setup
@@ -1,3 +1,18 @@
 #!/bin/bash
 
-/usr/bin/python /usr/lib/efalive/lib/efaLiveSetup/maingui.py ~/.efalive >> /dev/null
+DIR=~/.efalive
+
+if [ $1 ]
+then
+    if [ -d $1 ]
+    then
+        DIR=$1
+    else
+        echo "Error, not a directory: $1"
+	exit 1
+    fi
+fi
+
+PYTHONPATH=.:$PYTHONPATH 
+PYTHONPATH=$PYTHONPATH python -m efalivesetup.maingui $DIR >> /dev/null
+
